### ISSUE TITLE
Pez on GitHub

### ISSUE THREAD

**Issue by leekelleher** [bentaylor/zep#1]
Hey @bentaylor!

I finally took notice of these warnings about Google Code shutting down and that we should move our code over to GitHub! :smile_cat: 

The Pez codebase is now here: https://github.com/vertino/pez
You have commit rights on the project, (of course) :+1: 

It's been fun to look over our old code, it all gets quite nostalgic.
You never know, maybe one day we'll finish it off? :sunglasses:

**Comment by bentaylor** [comment]
It is fun to looks over the old code. I started zep to learn how to use Git, and to further my knowledge of PHP. Anything I could figure out and contribute to Pez, I would push to the Google Code page, but yeah, that's dead now. I was also hoping to learn enough to work on a fantasy baseball type game, but I just got wrapped up in other things.

Hopefully, we finish this one day so that we can say, "Hey, it's done," but seven years later, we maybe better off burning it to the ground and starting over from scratch, LOL
